version:  '2.2'
services:
    code-resources:
        image: tianon/true
        volumes:
            - ${CODE_VOLUMES}:/var/www/html/
    mysql:
        build: ./mysql
        ports:
            - "${MYSQL_HTTP_PORT}:3306"
        volumes:
            - ${MYSQL_DATA_PATH}:/var/lib/mysql/
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_INIT_SQL=${MYSQL_INIT_SQL}
        networks:
            - backend

    php:
        build:
            context: ./php
            dockerfile: "Dockerfile-${PHP_VERSION}"
        volumes_from:
            - code-resources
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend

    nginx:
        build: ./nginx
        ports:
            - "${NGINX_HTTP_PORT}:80"
        volumes_from:
            - code-resources
        volumes:
            - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/
        networks:
            - frontend
            - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"