version:  '2.1'
services:
    code-resources:
        image: tianon/true
        volumes:
            - /d/CODE/:/var/www/html/
    mysql-image:
        build: ./mysql
        container_name: mysql-container
        ports:
            - "23306:3306"
        volumes:
            - /d/docker/data/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_DATABASE=develop
            - MYSQL_USER=develop
            - MYSQL_PASSWORD=develop
            - MYSQL_ROOT_PASSWORD=root
            - INIT_SHELL=init.sh
            - INIT_SQL=init.sql

    php-image:
        build: ./php
        container_name: php-container
        links:
            - "mysql-image:database-server"
        volumes_from:
            - code-resources
        extra_hosts:
            - "dockerhost:192.168.10.50"

    nginx-image:
        build: ./nginx
        container_name: nginx-container
        ports:
            - "20080:80"
            - "28080:8080"
        links:
            - "php-image:php-server"
        volumes_from:
            - code-resources